# Generated by Django 5.2.10 on 2026-04-25 05:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Announcements',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('file', models.CharField(max_length=100)),
                ('uploaded_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'announcements',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Books',
            fields=[
                ('book_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('series_name', models.CharField(max_length=100)),
                ('class_field', models.CharField(db_column='class', max_length=20)),
                ('path', models.CharField(blank=True, max_length=150, null=True)),
            ],
            options={
                'db_table': 'books',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('purchase_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('purchase_date', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'purchase',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PurchaseItems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valid_upto', models.DateField()),
                ('sent_to_school', models.BooleanField(blank=True, null=True)),
                ('ebook_access', models.BooleanField(default=False)),
                ('keybook_access', models.BooleanField(default=False)),
                ('question_paper_access', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'purchase_items',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='School',
            fields=[
                ('school_name', models.CharField(max_length=150)),
                ('school_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('contact', models.CharField(blank=True, max_length=15, null=True)),
                ('password_hash', models.CharField(max_length=200)),
                ('branch', models.CharField(blank=True, max_length=150, null=True)),
                ('email', models.CharField(blank=True, max_length=255, null=True)),
                ('contact_person', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'school',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SharedQuestionPaper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exam_type', models.CharField(max_length=100)),
                ('file', models.FileField(upload_to='question_papers/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='samsel_website.school')),
            ],
            options={
                'db_table': 'shared_question_paper',
            },
        ),
        migrations.CreateModel(
            name='Syllabus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='syllabus/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='samsel_website.school')),
            ],
            options={
                'db_table': 'syllabus',
            },
        ),
    ]
